apiVersion: v1
kind: Service
metadata:
  name: service-service
spec:
  type: NodePort # this makes aour service external 
  selector:
    app: service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100 # external sevice need this in ports which must be in range of 30000 to something like 32000
      # for accessing your app from outside you call minikubeip:nodePort